AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MeVerse serverless backend.

Globals:
  Function:
    Timeout: 60

Parameters:
  StageName:
    Type: String
    Default: dev
  AssetBucketName:
    Type: String
    Default: meverse-dev

Resources:
  AssetBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref AssetBucketName

  AssetTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Asset
      PrimaryKey: 
        Name: WalletAddress
        Type: String
  
  MetadataLinkTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MetadataLink
      PrimaryKey:
        Name: TokenId
        Type: Number

  WalletTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Wallet
      PrimaryKey:
        Name: WalletAddress
        Type: String

  GetMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/getMetadata/
      Handler: index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          REGION: eu-central-1
          DYNAMO_METADATA_TABLE: MetadataLink
          METADATA_URI: https://ipfs.io/ipfs
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AssetBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataLinkTable
      Events:
        GetMetadata:
          Type: Api
          Properties:
            Path: /metadata/{id}
            Method: GET

  UploadAssetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/uploadAsset/
      Handler: index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          REGION: eu-central-1
          DYNAMO_METADATA_TABLE: MetadataLink
          DYNAMO_WALLET_TABLE: Wallet
          S3_BUCKET: meverse-dev
          METADATA_URI: https://ipfs.io/ipfs
          PINATA_KEY: 2027bc27eac9e5f17c6c
          PINATA_SECRET_KEY: f1ac9cf42ba99fc8777849d778e6ab02a41f4bb4b035aa7aa738f83191c0217d
          CONTRACT_ADDRESS: "0x3546FEBDD6EE3136575FAE0678F9827dd8488487"
          ALCHEMY_API_URL: https://eth-ropsten.alchemyapi.io/v2/ynTekJ0k_wI1iLLwiU8B285JZTqyoxt5
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AssetBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WalletTable

      Events:
        UploadAsset:
          Type: Api
          Properties:
            Path: /upload
            Method: POST

  GenerateAssetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/generateAsset/
      Handler: app.handler.lambda_handler
      Runtime: python3.8
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AssetBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref AssetTable
      Events:
        GenerateAsset:
          Type: Api
          Properties:
            Path: /generate
            Method: POST

Outputs:
  MeVerseApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/"